from __future__ import annotations

import argparse
import json
import logging
from typing import Dict

import weaviate


# ------------------------------------------------------------------
# Logging
# ------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)


# ------------------------------------------------------------------
# Validator (NO EMBEDDINGS HERE)
# ------------------------------------------------------------------
def validate_chunk(chunk_uuid: str, properties: Dict) -> bool:
    """
    Validate an editorial chunk before upsert.

    Returns True ONLY if the chunk is safe to insert.
    """

    # ---- Required content ----
    content = properties.get("content")
    if not isinstance(content, str) or not content.strip():
        logger.warning("Skipping %s: Missing or empty content", chunk_uuid)
        return False

    # ---- Canonical Game reference (No Orphan Rule) ----
    game_ref = properties.get("game")
    if not isinstance(game_ref, dict) or "beacon" not in game_ref:
        logger.warning("Skipping %s: Missing canonical game reference", chunk_uuid)
        return False

    # ---- Source integrity ----
    if properties.get("source") != "gamespot":
        logger.warning("Skipping %s: Invalid source", chunk_uuid)
        return False

    # ---- Content type gate ----
    content_type = properties.get("content_type")
    if content_type not in {"review", "article"}:
        logger.warning("Skipping %s: Invalid content_type", chunk_uuid)
        return False

    return True


# ------------------------------------------------------------------
# Orchestration: Validate → Upsert
# ------------------------------------------------------------------
def upsert_editorial_file(
    client: weaviate.WeaviateClient,
    file_path: str,
) -> None:
    """
    Load editorial chunk payloads, validate, and upsert them into Weaviate.
    """

    # --------------------------------------------------
    # 1. Load payloads
    # --------------------------------------------------
    with open(file_path, "r", encoding="utf-8") as f:
        payloads = json.load(f)

    if not isinstance(payloads, list):
        raise ValueError("Editorial payload file must contain a list")

    total = len(payloads)
    upserted = 0
    skipped = 0

    # --------------------------------------------------
    # 2. Get Collection (Weaviate v4)
    # --------------------------------------------------
    collection = client.collections.get("EditorialChunk")

    # --------------------------------------------------
    # 3. Batch Insert
    # --------------------------------------------------
    with collection.batch.dynamic() as batch:
        for obj in payloads:
            chunk_uuid = obj.get("uuid")
            properties = obj.get("properties", {})

            if not chunk_uuid:
                logger.warning("Skipping object with missing UUID")
                skipped += 1
                continue

            # ---- Validation Gate ----
            if not validate_chunk(chunk_uuid, properties):
                skipped += 1
                continue

            # ---- Upsert (vector generated by text2vec-transformers) ----
            batch.add_object(
                uuid=chunk_uuid,
                properties=properties,
            )
            upserted += 1

    # --------------------------------------------------
    # 4. Batch Error Handling
    # --------------------------------------------------
    failed = collection.batch.failed_objects or []
    for failure in failed:
        logger.warning(
            "EditorialChunk upsert failed (UUID=%s): %s",
            getattr(failure.object_, "uuid", "UNKNOWN"),
            failure.error,
        )

    # --------------------------------------------------
    # 5. Summary
    # --------------------------------------------------
    print(
        f"Processed {total}. "
        f"Upserted {upserted}. "
        f"Skipped {skipped}."
    )


# ------------------------------------------------------------------
# CLI Entrypoint
# ------------------------------------------------------------------
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Validate & Upsert Editorial Chunks (text2vec-transformers)"
    )
    parser.add_argument(
        "--file",
        required=True,
        help="Path to editorial chunk payload JSON file",
    )

    args = parser.parse_args()

    client = weaviate.connect_to_local()

    try:
        upsert_editorial_file(
            client=client,
            file_path=args.file,
        )
    finally:
        client.close()
